import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Map from 'react-map-gl'
import DeckGL from '@deck.gl/react';
import {useState} from 'react';
import { LosAngelesActiveBusinessLayer } from '../layers/hexagon/Los-angeles-active-businesses'
import { NewYorkTreesLayer } from '@/layers/scatterplot/new-york-trees';

const MAPBOX_TOKEN = 'pk.eyJ1IjoieXV5YWZ1amltb3RvIiwiYSI6ImNsZWdyZDA4NTA1ZGwzeG53Y2c2OGY0bjAifQ._mbKMYj_moCfX1GcJmxAJg'

const layers = {
  '1': NewYorkTreesLayer,
  '2': LosAngelesActiveBusinessLayer
}

export default function Home() {

  const [layerId, setLayerId] = useState('2');
  const {LayerClass, layerOptions} = layers[layerId];

  const layer = new LayerClass(layerOptions);

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{zIndex:10000}}>
          <button onClick={() => setLayerId('1')}>New York Trees</button>
          <button onClick={() => setLayerId('2')}>Los Angeles Active Businesses</button>
        </div>
        <DeckGL
          initialViewState={layer.initialViewState}
          controller={true}
          layers={[layer.layer]}
        >
          <Map
            style={{width: '100vw', height: '100vh'}}
            mapStyle="mapbox://sprites/mapbox/dark-v8"
            mapboxAccessToken={MAPBOX_TOKEN}
          />
        </DeckGL>
      </main>
    </>
  )
}
